// Fetches the backend's cross-module "recent completed reports" registry
// (GET /api/reports/recent — see reportRegistry.ts / reportsAggregatorService.ts
// on ai-insights-api) and converts each one into a REAL HistoryEntry — same
// shape saveToHistory() would have produced had the report been generated
// through the frontend UI — so it renders identically in the Reports
// Library (and, via View, in the module's own page) whether it was
// generated by a browser session or by hitting the API directly (curl,
// another service, anything outside this frontend).
//
// The conversion is per-module because each module's page component saves a
// different field shape (see the grep'd saveToHistory() calls this was
// built from). 23 of the 25 modules that register jobs have a known,
// working History shape today; the other 2 (Objection Handling, Content
// Generation) and the two newest modules (Competition Benchmarking, Job
// Description Parser) never had rich History rendering wired up even for
// browser-generated reports, so there's no "look like other reports" target
// to match — those fall back to a lightweight row with a raw-JSON link,
// same as before this change.

import { API_ENDPOINTS, API_URL } from './config';
import { saveToHistory } from './history';
import type { HistoryEntry, ModuleType } from './history';
import type { StrategyFramework } from '@ai-insights/types';

interface RecentReportSummary {
  jobId: string;
  moduleType: string;
  label: string;
  status: string;
  createdAt: string;
  completedAt?: string;
}

// moduleType (as registered server-side) → actual mounted API path segment.
// Almost all match 1:1; a few don't (the registered moduleType matches the
// frontend's ModuleType/history naming, not the route's own path segment).
const API_PATH_OVERRIDES: Record<string, string> = {
  // industry-blog and industry-thought-leadership both register under their
  // real sub-moduleType (see contentGeneration.ts's registerJobStart call —
  // needed so hydrateFields() below can tell them apart), but the route
  // itself is still only mounted at /api/content-generation.
  'industry-blog': 'content-generation',
  'industry-thought-leadership': 'content-generation',
  'peer-benchmarking': 'benchmark',
  'business-themes': 'themes',
};

export function apiPathForModuleType(moduleType: string): string {
  return API_PATH_OVERRIDES[moduleType] || moduleType;
}

async function fetchRecentReports(): Promise<RecentReportSummary[]> {
  try {
    const res = await fetch(`${API_ENDPOINTS.reportsRecent}?limit=200`);
    if (!res.ok) return [];
    const data = await res.json();
    return (data.reports || []) as RecentReportSummary[];
  } catch {
    return [];
  }
}

async function fetchRawJob(moduleType: string, jobId: string): Promise<Record<string, unknown> | null> {
  try {
    const res = await fetch(`${API_URL}/api/${apiPathForModuleType(moduleType)}/${jobId}`);
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

const DEDUPE_WINDOW_MS = 60_000; // treat a local entry within 1 min of an API report's completedAt, same moduleType + label, as the same report

function isDuplicateOfLocalEntry(report: RecentReportSummary, localEntries: HistoryEntry[]): boolean {
  if (!report.completedAt) return false;
  const reportMs = new Date(report.completedAt).getTime();
  return localEntries.some((e) => {
    if (e.moduleType !== report.moduleType) return false;
    const localMs = new Date(e.completedAt).getTime();
    if (Math.abs(localMs - reportMs) > DEDUPE_WINDOW_MS) return false;
    const label = (e.targetCompany || '').toLowerCase().trim();
    return label && label === report.label.toLowerCase().trim();
  });
}

// Per-module field mapping — mirrors each module's own saveToHistory() call
// exactly (field names and sources), so a hydrated API entry is
// indistinguishable from a browser-generated one once built.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function hydrateFields(moduleType: string, raw: any, label: string): Partial<HistoryEntry> | null {
  switch (moduleType) {
    case 'financial-analysis':
      return { financialData: raw };
    case 'marketing-strategy':
      if (raw.vuca4w1hMatrix) {
        return { strategyIndustry: label, strategyFramework: 'VUCA × 4W1H' as StrategyFramework, vucaResult: raw };
      }
      return {
        strategyIndustry: raw.industryOrSegment, strategyFramework: raw.framework,
        strategySummary: raw.frameworkSummary, strategyDimensions: raw.dimensions,
        strategyRecommendations: raw.strategicRecommendations,
      };
    case 'it-jobs':
      return { companyDomain: raw.companyDomain, itJobData: raw };
    case 'niche-industries':
      return { nicheIndustryVertical: label, nicheTopics: raw.topics };
    case 'industry-outsourcing-report':
      return { outsourcingReportData: raw };
    case 'challenges-growth':
      return { challengesGrowthRows: raw.rows };
    case 'sales-play-2':
      return { salesPlay2Data: raw };
    case 'consulting-intelligence':
      return { consultingTopic: label, consultingFirms: raw.discoveredFirms || [], consultingResult: raw };
    case 'firmographic':
      return { companyDomain: raw.companyDomain, firmographicData: raw };
    case 'gcc-sales-play':
      return { gccSalesPlayData: raw };
    case 'industry-trends':
      return { industryBusinessTrends: raw.businessTrends, industryTechTrends: raw.techTrends, industryGeography: raw.geography || 'Global' };
    case 'spend':
      return { companyDomain: raw.companyDomain, spendData: raw };
    case 'vuca-analysis':
      return { vucaIndustry: label, vucaGeography: raw.geography, vucaResult: raw };
    case 'sales-play':
      return { salesPlayData: raw };
    case 'key-buyers':
      return { keyBuyerRows: raw.rows };
    case 'business-themes': // themes.ts serves business/technology/sustainability off one route — themeType comes from the raw job itself
      return { themeType: raw.themeType, themeRows: raw.rows };
    case 'industry-report':
      return {
        industryReportQuery: raw.query || label, industryReportScope: raw.scope,
        industryReportSections: raw.sections, industryReportMarketSizing: raw.marketSizing,
        industryReportExecutiveSummary: raw.executiveSummary,
      };
    case 'industry-thought-leadership':
      return { thoughtLeadershipTitle: raw.title, thoughtLeadershipContent: raw.content };
    // peers is currently unreachable here: its backend route is synchronous
    // (no jobId/poll pattern), so nothing ever registers it into the job
    // registry this whole mechanism reads from — a pre-existing
    // architectural difference, not something fixable from this file.
    // Kept ready in case that route becomes job-based. business-description
    // used to have the same gap but was converted to the async job pattern.
    case 'business-description':
      return { businessDescription: raw.description, companyDomain: raw.domain };
    case 'business-segments':
      return { businessSegmentsData: raw };
    case 'peer-benchmarking':
      return {
        userOrganization: raw.userOrganization, industryContext: raw.industryContext,
        selectedPeers: raw.selectedPeers, benchmarkingTable: raw.benchmarkingTable, gapAnalysis: raw.gapAnalysis,
      };
    case 'peers':
      return { companyDomain: raw.companyDomain, peerCompanies: raw.peerCompanies || raw.peers };
    case 'technology-heat-map':
      return { techHeatMapRows: raw.rows, techHeatMapHeadline: raw.headline, techHeatMapGeography: raw.geography };
    case 'business-timelines':
      return { businessTimelinesData: raw };
    case 'industry-blog':
      return { blogTitle: raw.title, blogContent: raw.content, blogHashtags: raw.hashtags };
    default:
      return null; // no known rich shape — caller falls back to a lightweight row
  }
}

// Lightweight fallback for modules with no known History field mapping —
// just enough for the list row; View opens the raw JSON. Not persisted to
// localStorage (nothing rich to restore later), so re-fetched every page
// load — cheap, and always reflects current registry/job-store state.
function toLightweightHistoryEntry(report: RecentReportSummary): HistoryEntry | null {
  const completedAt = report.completedAt || report.createdAt;
  if (!completedAt) return null;
  return {
    id: `api:${report.moduleType}:${report.jobId}`,
    moduleType: report.moduleType as ModuleType,
    targetCompany: report.label,
    completedAt,
    sourceKind: 'api-raw',
    apiJobId: report.jobId,
    apiCreatedAt: report.createdAt,
  };
}

// Fetches each not-yet-local report's full data, and where a field mapping
// exists, PERSISTS it via saveToHistory — at that point it's a genuine local
// entry indistinguishable from one the module's own page would have saved
// (View restores it normally, export works normally, and it won't be
// re-fetched on the next page load since it's now a real local entry).
// Only returns the lightweight, non-persisted fallback rows — hydrated ones
// are already in the store the caller's next loadHistory() call will read.
export async function syncApiOnlyReports(localEntries: HistoryEntry[]): Promise<HistoryEntry[]> {
  const reports = await fetchRecentReports();
  const toFetch = reports.filter((r) => !isDuplicateOfLocalEntry(r, localEntries));

  const lightweight = await Promise.all(toFetch.map(async (r) => {
    const raw = await fetchRawJob(r.moduleType, r.jobId);
    const fields = raw ? hydrateFields(r.moduleType, raw, r.label) : null;
    if (fields) {
      saveToHistory({
        moduleType: r.moduleType as ModuleType,
        targetCompany: r.label,
        completedAt: r.completedAt || r.createdAt,
        apiJobId: r.jobId,
        apiCreatedAt: r.createdAt,
        ...fields,
      });
      return null; // now local — picked up by the caller's next loadHistory()
    }
    return toLightweightHistoryEntry(r);
  }));

  return lightweight.filter((e): e is HistoryEntry => e !== null);
}
