// Fetches the backend's cross-module "recent completed reports" registry
// (GET /api/reports/recent — see reportRegistry.ts / reportsAggregatorService.ts
// on ai-insights-api) and merges it with the browser's own localStorage
// history, so a report generated by hitting a module's API directly (curl,
// another service — anything that isn't this frontend's own browser
// session) shows up in Report History too, not just ones saved via the UI.

import { API_ENDPOINTS } from './config';
import type { HistoryEntry, ModuleType } from './history';

interface RecentReportSummary {
  jobId: string;
  moduleType: string;
  label: string;
  status: string;
  createdAt: string;
  completedAt?: string;
}

// moduleType (as registered server-side) → actual mounted API path segment.
// Almost all match 1:1; two don't (the registered moduleType matches the
// frontend's ModuleType/history naming, not the route's own path segment).
const API_PATH_OVERRIDES: Record<string, string> = {
  'peer-benchmarking': 'benchmark',
  'business-themes': 'themes',
};

export function apiPathForModuleType(moduleType: string): string {
  return API_PATH_OVERRIDES[moduleType] || moduleType;
}

async function fetchRecentReports(): Promise<RecentReportSummary[]> {
  try {
    const res = await fetch(`${API_ENDPOINTS.reportsRecent}?limit=200`);
    if (!res.ok) return [];
    const data = await res.json();
    return (data.reports || []) as RecentReportSummary[];
  } catch {
    return [];
  }
}

const DEDUPE_WINDOW_MS = 60_000; // treat a local entry within 1 min of an API report's completedAt, same moduleType + label, as the same report

function isDuplicateOfLocalEntry(report: RecentReportSummary, localEntries: HistoryEntry[]): boolean {
  if (!report.completedAt) return false;
  const reportMs = new Date(report.completedAt).getTime();
  return localEntries.some((e) => {
    if (e.moduleType !== report.moduleType) return false;
    const localMs = new Date(e.completedAt).getTime();
    if (Math.abs(localMs - reportMs) > DEDUPE_WINDOW_MS) return false;
    const label = (e.targetCompany || '').toLowerCase().trim();
    return label && label === report.label.toLowerCase().trim();
  });
}

// Builds a minimal-but-valid HistoryEntry for an API-only report — just
// enough for the Reports Library's title/type/date/cost columns. Rich
// per-module fields are deliberately absent; `sourceKind: 'api'` tells the
// UI to show a "View Raw" link (to the module's own GET /:jobId) instead of
// the normal rendered-report view/export actions, which need those fields.
function toSyntheticHistoryEntry(report: RecentReportSummary): HistoryEntry | null {
  const completedAt = report.completedAt || report.createdAt;
  if (!completedAt) return null;
  return {
    id: `api:${report.moduleType}:${report.jobId}`,
    moduleType: report.moduleType as ModuleType,
    targetCompany: report.label,
    completedAt,
    sourceKind: 'api',
    apiJobId: report.jobId,
    apiCreatedAt: report.createdAt,
  };
}

// Returns API-sourced entries not already represented in `localEntries` —
// call this alongside loadHistory() and concat the results.
export async function fetchApiOnlyReportEntries(localEntries: HistoryEntry[]): Promise<HistoryEntry[]> {
  const reports = await fetchRecentReports();
  const result: HistoryEntry[] = [];
  for (const r of reports) {
    if (isDuplicateOfLocalEntry(r, localEntries)) continue;
    const entry = toSyntheticHistoryEntry(r);
    if (entry) result.push(entry);
  }
  return result;
}
